use fiap_bank_ejb;
INSERT INTO BANCO (NOME) VALUES ('FIAP BANK');
INSERT INTO AGENCIA (BANCO_ID) VALUES (1);
INSERT INTO TIPO_CONTA (DESCRICAO) VALUES ('CORRENTE');

INSERT INTO ENDERECO (LOGRADOURO,NUMERO,BAIRRO,UF,MUNICIPIO,CEP)
VALUES ('Av. Aclimação','1264','Aclimação','SP','São Paulo','01538-001');
INSERT INTO ENDERECO (LOGRADOURO,NUMERO,BAIRRO,UF,MUNICIPIO,CEP)
VALUES ('Av. Aclimação','1264','Aclimação','SP','São Paulo','01538-001');

INSERT INTO USUARIO (NOME,RG,CPF,TELEFONE,ENDERECO_ID)
VALUES ('Gerente Fiap','999999999','99999999999','11 3385 8010',1);
INSERT INTO USUARIO (NOME,RG,CPF,TELEFONE,ENDERECO_ID)
VALUES ('Cliente Fiap','888888888','88888888888','11 3385 8010',2);

INSERT INTO SEGURANCA (SENHA,FRASE_SECRETA,PERFIL,LOGIN)
VALUES ('gerente',null,'GERENTE','gerente');
INSERT INTO SEGURANCA (SENHA,FRASE_SECRETA,PERFIL,LOGIN)
VALUES ('cliente',null,'CLIENTE','000001');

INSERT INTO CONTA (SEGURANCA_ID,TIPO_CONTA_ID,AGENCIA_ID,CODIGO_CONTA)
VALUES (2,1,1,'000001');

INSERT INTO CORRENTISTA (GASTO_MENSAL_APROXIMADO,RENDA_MENSAL,VALOR_TOTAL_PATRIMONIO,CONTA_ID,USUARIO_ID)
VALUES (600.00,900.00,20000.00,1,2);

INSERT INTO FUNCIONARIO (USUARIO_ID,SEGURANCA_ID,AGENCIA_ID)
VALUES (1,1,1);